# -*- coding: utf-8 -*-
"""Ryan_Nguyen_Chatbot.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mI8sSPwOtETg78ZgNfGTZCYK3XNlUYSC

# Healthcare Chatbot

## Set up
"""

# Install core libraries and dependencies
print("Installing project dependencies...")

# Core Hugging Face/NLP libraries
!pip install -q transformers==4.* torch --upgrade

# Gradio for the UI
!pip install -q gradio==4.*

# Sentence-Transformers (for RAG embeddings)
!pip install -q sentence-transformers

# FAISS (for high-speed vector indexing)
!pip install -q faiss-cpu

# Utility libraries (scikit-learn for TF-IDF/utilities, pandas for data)
!pip install -q scikit-learn pandas numpy

print("\nInstallation complete. You can proceed to the next step.")

"""## Clone Github Repo"""

# --- COLAB-GITHUB INTEGRATION ---

# 1. Configuration based on your GitHub link
GITHUB_USERNAME = "ryrynbob"
REPO_NAME = "Healthcare-Chatbot" # <<--- CORRECTED TO MATCH YOUR REPO NAME

# 2. Get your Personal Access Token (PAT)
# You need a PAT for Colab to push/pull from GitHub.
# If you run into issues, try creating a new PAT on GitHub with 'repo' scope access.
from getpass import getpass
GIT_TOKEN = getpass("Enter your GitHub Personal Access Token (PAT): ")

# 3. Clone the repository
!git clone https://{GIT_TOKEN}@github.com/{GITHUB_USERNAME}/{REPO_NAME}.git

# 4. Change directory into the cloned folder
import os
os.chdir(REPO_NAME) # <<--- DIRECTORY CHANGE IS NOW CORRECT
print(f"\nChanged working directory to: {os.getcwd()}")

# 5. Verify the connection and files
print("\nFiles in your project folder:")
!ls

"""## Create Json healthcare file"""

# --- Task 2: Data Curation ---

# 1. Define the correct structure for your Knowledge Base (KB)
# Each entry needs a unique ID, a question, and a corresponding answer.
knowledge_base_data = [
    {
        "id": "faq_01",
        "question": "What is a balanced diet and why is it important?",
        "answer": "A balanced diet includes a variety of foods from all food groups, supplying the necessary nutrients (protein, carbs, fats, vitamins, minerals, and water) for your body to function correctly. It helps maintain a healthy weight and supports energy levels."
    },
    {
        "id": "faq_02",
        "question": "How much water should I drink per day?",
        "answer": "The general recommendation is about 8 glasses (64 ounces) per day, but this varies based on your body weight, activity level, and climate. Listen to your body and drink whenever you feel thirsty."
    },
    {
        "id": "faq_03",
        "question": "What are the benefits of regular exercise?",
        "answer": "Regular exercise boosts mood, strengthens bones and muscles, reduces the risk of chronic diseases (like heart disease and type 2 diabetes), and helps manage weight."
    },
    {
        "id": "faq_04",
        "question": "What is the recommended amount of sleep for an adult?",
        "answer": "Most adults need between 7 and 9 hours of quality sleep per night for optimal health and cognitive function."
    },
    # -----------------------------------------------------------
    # CRITICAL: ADD AT LEAST 46 MORE HIGH-QUALITY Q&A PAIRS HERE!
    # -----------------------------------------------------------
    {
        "id": "faq_50_or_more",
        "question": "What is the difference between aerobic and anaerobic exercise?",
        "answer": "Aerobic exercise (like running or swimming) uses oxygen to generate energy and can be sustained for a long time. Anaerobic exercise (like sprinting or weightlifting) involves short bursts of intense activity without using oxygen."
    }
]

# 2. Save the data to the JSON file
import json
file_path = "healthcare_data.json"

with open(file_path, 'w') as f:
    json.dump(knowledge_base_data, f, indent=4)

print(f"Successfully created and saved {len(knowledge_base_data)} entries to '{file_path}'")

"""## Commit and push"""

# --- Task 2: Version Control (Save to GitHub) ---

# Set your Git identity (necessary for committing in a new environment)
!git config --global user.email "ryanpanic6@gmail.com" # Replace with your GitHub email
!git config --global user.name "ryrynbob"    # Replace with your GitHub username

# 1. Check the status of your files
print("Git Status:")
!git status

# 2. Add the new/modified file(s) to the commit
!git add healthcare_data.json

# 3. Commit the changes
!git commit -m "Task 2: Initial 50+ entry Knowledge Base (healthcare_data.json)"

# 4. Push the changes to GitHub
print("\nPushing changes to GitHub...")
!git push

# Configuration
GITHUB_USERNAME = "ryrynbob"
REPO_NAME = "Healthcare-Chatbot"

# Re-Authentication is required for cloning/pushing
from getpass import getpass
print("Re-authenticating and re-cloning to fix the directory state.")
GIT_TOKEN = getpass("Enter your GitHub Personal Access Token (PAT): ")

# 1. CLEAN UP and RE-CLONE
# Delete the old, broken repository folder to prevent naming conflicts (e.g., 'Healthcare-Chatbot(1)')
print(f"\nRemoving old '{REPO_NAME}' directory...")
!rm -rf $REPO_NAME
# Re-clone the repository from GitHub
!git clone https://{GIT_TOKEN}@github.com/{GITHUB_USERNAME}/{REPO_NAME}.git
print(f"Successfully re-cloned the repository.")

# 2. MOVE THE DATA FILE
# Your 'healthcare_data.json' file was created, but it's likely sitting outside the repository folder.
# We must move it into the newly cloned folder before committing.
try:
    # This command moves the file from the Colab root into the cloned folder
    !mv healthcare_data.json $REPO_NAME/
    print(f"Successfully moved healthcare_data.json into the '{REPO_NAME}' folder.")
except Exception as e:
    # If the file wasn't found in the root, it might have been saved in the repo before the error.
    print(f"\nCould not find 'healthcare_data.json' in the root directory. Assuming it is already inside the repo folder.")
    pass

# 3. CHANGE DIRECTORY
import os
os.chdir(REPO_NAME)
print(f"\nChanged working directory to: {os.getcwd()}")

# 4. FINAL COMMIT AND PUSH
print("\n--- Running Final Commit and Push ---")
# Set Git identity (if not already set for the session)
# 🚨 REPLACE WITH YOUR ACTUAL GITHUB CREDENTIALS 🚨
!git config --global user.email "your.email@example.com"
!git config --global user.name "Your GitHub Username"

# Add the file (it will be added/updated in the Git index)
!git add healthcare_data.json

# Commit the changes
!git commit -m "Task 2: Finalized 50+ entry Knowledge Base and fixed Git state"

# Push the changes to GitHub
print("\nPushing changes to GitHub...")
!git push

"""## Load Model Sentence Trasmformers"""

from sentence_transformers import SentenceTransformer

model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")

sentences = [
    "That is a happy person",
    "That is a happy dog",
    "That is a very happy person",
    "Today is a sunny day"
]
embeddings = model.encode(sentences)

similarities = model.similarity(embeddings, embeddings)
print(similarities.shape)
# [4, 4]

"""## Check Files"""

# Commented out IPython magic to ensure Python compatibility.
import os

# 1. Go into the cloned repo folder
# %cd /content/Healthcare-Chatbot

# 2. Confirm the files are there
print("CWD:", os.getcwd())
print("Files:", os.listdir())

# Commented out IPython magic to ensure Python compatibility.
# Go to base directory
# %cd /content

# Optional: delete any previous copies of the repo
!rm -rf Healthcare-Chatbot

# Clone again (public repo -> no token needed)
!git clone https://github.com/ryrynbob/Healthcare-Chatbot.git

# Move into the repo folder
# %cd Healthcare-Chatbot

# List files inside the repo
import os
print("Now in:", os.getcwd())
print("Repo files:", os.listdir())

import os

print("Current working directory:", os.getcwd())
print("Files here:", os.listdir())

# Json sanity check

import json

with open("healthcare_data.json", "r", encoding="utf-8") as f:
    kb = json.load(f)

print("Entries in KB:", len(kb))
print("First item:", kb[0])

# Make sure app.py using right path
import json

KB_PATH = "healthcare_data.json"  # same folder as app.py

with open(KB_PATH, "r", encoding="utf-8") as f:
    knowledge_base = json.load(f)

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/Healthcare-Chatbot
!python app.py

import os

print("CWD:", os.getcwd())
print("Exists healthcare_data.json?", os.path.isfile("healthcare_data.json"))

import json
import os

KB_PATH = "healthcare_data.json"  # file in the same folder as app.py

with open(KB_PATH, "r", encoding="utf-8") as f:
    kb_data = json.load(f)

"""## Sanity check to make sure we on track with repo"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/Healthcare-Chatbot
!ls

!pip install sentence-transformers faiss-cpu numpy

# Load KB and split q's and a's

import json

with open("healthcare_data.json", "r", encoding="utf-8") as f:
    kb = json.load(f)

print("Number of entries:", len(kb))
print(kb[0])

questions = [item["question"] for item in kb]
answers = [item["answer"] for item in kb]

print("Example question:", questions[0])
print("Example answer:", answers[0])

"""## Initialize and Model Data"""

# Load embedding model
from sentence_transformers import SentenceTransformer

def load_embedding_model():
    model_name = "sentence-transformers/all-MiniLM-L6-v2"
    model = SentenceTransformer(model_name)
    print("Loaded embedding model:", model_name)
    return model

embedding_model = load_embedding_model()

import json
import os
import torch
from sentence_transformers import SentenceTransformer
import faiss  # FAISS will handle the efficient search
import numpy as np
from transformers import pipeline

# --- Configuration ---
KB_FILE = "healthcare_data.json"
INDEX_FILE = "faq.index"
EMBEDDING_MODEL_NAME = "sentence-transformers/all-MiniLM-L6-v2"
GENERATOR_MODEL_NAME = "google/flan-t5-base"

# Global Variables
KB = []  # Will store the loaded JSON data
KB_QUESTIONS = []  # Will store only the questions for indexing

# 1. Load the Knowledge Base (KB)
def load_knowledge_base():
    """Loads the Q&A data from the JSON file."""
    global KB, KB_QUESTIONS
    try:
        with open(KB_FILE, 'r') as f:
            KB = json.load(f)
            KB_QUESTIONS = [item['question'] for item in KB]
            print(f"Loaded {len(KB)} entries from {KB_FILE}")
            return True
    except FileNotFoundError:
        print(f"Error: {KB_FILE} not found. Please ensure it is in the correct directory.")
        return False

# Initialize the data
load_knowledge_base()

"""## Create embeddings and FAISS index"""

import numpy as np
import faiss

# 1. Encode all questions into embeddings
question_embeddings = embedding_model.encode(
    questions,
    convert_to_numpy=True,
    show_progress_bar=True
)

print("Embeddings shape:", question_embeddings.shape)  # (50, 384) or similar

# 2. Convert to float32 for FAISS
question_embeddings = question_embeddings.astype("float32")

# 3. Normalize for cosine similarity
faiss.normalize_L2(question_embeddings)

# 4. Build a simple FAISS index (inner product -> cosine because we normalized)
dim = question_embeddings.shape[1]
index = faiss.IndexFlatIP(dim)
index.add(question_embeddings)

print("Index size (number of vectors):", index.ntotal)

"""## Define helper to retrieve best answer"""

def retrieve_answers(query, k=3):
    """
    Given a user query, return the top-k matched Q&A pairs from the KB.
    """
    # Embed the query
    query_emb = embedding_model.encode([query], convert_to_numpy=True)
    query_emb = query_emb.astype("float32")
    faiss.normalize_L2(query_emb)

    # Search in FAISS index
    distances, indices = index.search(query_emb, k)

    results = []
    for score, idx in zip(distances[0], indices[0]):
        results.append({
            "kb_id": kb[idx]["id"],
            "kb_question": questions[idx],
            "kb_answer": answers[idx],
            "similarity": float(score)
        })
    return results

def answer_question(query, k=3):
    """
    Simple retrieval-based answer: returns the best matched FAQ answer.
    """
    results = retrieve_answers(query, k=k)
    best = results[0]
    print(f"User query: {query}")
    print(f"Matched FAQ: {best['kb_question']}")
    print(f"Similarity: {best['similarity']:.3f}")
    print("\nAnswer:")
    print(best["kb_answer"])
    return best

"""## Test it"""

answer_question("What do beta blockers do?")

# a few more
answer_question("How does aspirin help with the heart?")
answer_question("What are common symptoms of a heart attack?")
answer_question("What is heart failure?")

"""## Check and save work 11/14"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/Healthcare-Chatbot
!ls

!git status

!git add app.py healthcare_data.json

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/Healthcare-Chatbot
!git status

!git add Ryan_Nguyen_Chatbot.py
# or, if it’s a notebook:
# !git add Ryan_Nguyen_Chatbot.ipynb

!git add Ryan_Nguyen_Chatbot.py faq.index